#!/bin/bash
#
# install.sh — Install Guezli/mailcow-f2b-feed into a local Crowdsec instance.
# Adds an acquisition for the netfilter-mailcow container, a parser for
# Mailcow's final-ban lines, and a trigger-scenario that propagates each
# ban into the local Crowdsec LAPI.
#
# Bans stay LOCAL (no push to remote LAPIs).
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/Guezli/crowdsec-mailcow-f2b-feed/main/install.sh | sudo bash
#   # or download first, inspect, then run:
#   curl -fsSL https://raw.githubusercontent.com/Guezli/crowdsec-mailcow-f2b-feed/main/install.sh -o /tmp/install.sh
#   less /tmp/install.sh
#   sudo bash /tmp/install.sh
#
set -euo pipefail

REPO_RAW="https://raw.githubusercontent.com/Guezli/crowdsec-mailcow-f2b-feed/main"
SCENARIO_DEST="/etc/crowdsec/scenarios/mailcow-f2b-feed.yaml"
PARSER_DEST="/etc/crowdsec/parsers/s01-parse/mailcow-f2b-bans.yaml"
ACQUIS_DEST="/etc/crowdsec/acquis.d/mailcow-f2b-feed.yaml"
CONTAINER_DEFAULT="mailcowdockerized-netfilter-mailcow-1"

color() { printf '\033[%sm%s\033[0m' "$1" "$2"; }
ok()    { echo "$(color '1;32' '✓') $*"; }
warn()  { echo "$(color '1;33' '!') $*"; }
fail()  { echo "$(color '1;31' '✗') $*" >&2; exit 1; }
info()  { echo "$(color '1;34' '→') $*"; }

[[ $EUID -eq 0 ]] || fail "Please run as root (or via sudo)."

# ── 1. Crowdsec installed? ─────────────────────────────────────────────
command -v cscli >/dev/null || fail "cscli not found — is Crowdsec installed on this host?"
ok "Crowdsec found ($(cscli version 2>&1 | grep -i 'version' | head -1 || true))"

mkdir -p /etc/crowdsec/scenarios /etc/crowdsec/parsers/s01-parse /etc/crowdsec/acquis.d

# ── 2. Detect Mailcow netfilter container ──────────────────────────────
command -v docker >/dev/null || fail "docker not found — Mailcow's netfilter-mailcow runs in a container."

NETFILTER_CONTAINER=$(docker ps --format '{{.Names}}' 2>/dev/null \
    | grep -E 'netfilter.*mailcow|mailcow.*netfilter' | head -1 || true)

if [[ -z "$NETFILTER_CONTAINER" ]]; then
    if docker ps -a --format '{{.Names}}' | grep -qE "$CONTAINER_DEFAULT"; then
        fail "Container $CONTAINER_DEFAULT exists but isn't running. Start Mailcow first."
    fi
    fail "No netfilter-mailcow container found. Is Mailcow installed and running on this host?"
fi
ok "Detected netfilter-mailcow container: $NETFILTER_CONTAINER"

# ── 3. Acquisition ─────────────────────────────────────────────────────
if [[ -f "$ACQUIS_DEST" ]]; then
    ok "Acquisition already exists: $ACQUIS_DEST — leaving it alone"
else
    cat > "$ACQUIS_DEST" <<EOF
---
# Auto-generated by Guezli/crowdsec-mailcow-f2b-feed install.sh
# netfilter-mailcow logs are plain-text (not JSON, not syslog).
# type: mailcow-f2b lets crowdsecurity/non-syslog parser set program=mailcow-f2b.
source: docker
container_name:
  - $NETFILTER_CONTAINER
labels:
  type: mailcow-f2b
EOF
    ok "Wrote acquisition: $ACQUIS_DEST"
fi

# ── 4. Install parser ──────────────────────────────────────────────────
info "Downloading parser from $REPO_RAW/parsers/s01-parse/mailcow-f2b-bans.yaml"
curl -fsSL -o "${PARSER_DEST}.new" "$REPO_RAW/parsers/s01-parse/mailcow-f2b-bans.yaml"
if [[ -f "$PARSER_DEST" ]] && cmp -s "$PARSER_DEST" "${PARSER_DEST}.new"; then
    rm -f "${PARSER_DEST}.new"
    ok "Parser already up-to-date"
else
    mv "${PARSER_DEST}.new" "$PARSER_DEST"
    chmod 644 "$PARSER_DEST"
    ok "Parser installed: $PARSER_DEST"
fi

# ── 5. Install scenario ────────────────────────────────────────────────
info "Downloading scenario from $REPO_RAW/scenarios/mailcow-f2b-feed.yaml"
curl -fsSL -o "${SCENARIO_DEST}.new" "$REPO_RAW/scenarios/mailcow-f2b-feed.yaml"
if [[ -f "$SCENARIO_DEST" ]] && cmp -s "$SCENARIO_DEST" "${SCENARIO_DEST}.new"; then
    rm -f "${SCENARIO_DEST}.new"
    ok "Scenario already up-to-date"
else
    mv "${SCENARIO_DEST}.new" "$SCENARIO_DEST"
    chmod 644 "$SCENARIO_DEST"
    ok "Scenario installed: $SCENARIO_DEST"
fi

# ── 6. Reload + verify ─────────────────────────────────────────────────
info "Reloading Crowdsec..."
if systemctl is-active --quiet crowdsec; then
    systemctl reload crowdsec
    sleep 2
    ok "Crowdsec reloaded"
else
    warn "Crowdsec service not active — start with: systemctl start crowdsec"
fi

if cscli scenarios list 2>/dev/null | grep -qE '\bGuezli/mailcow-f2b-feed\b'; then
    ok "Scenario active: Guezli/mailcow-f2b-feed"
else
    fail "Scenario not loaded. Check: journalctl -u crowdsec --since '1m ago'"
fi
if cscli parsers list 2>/dev/null | grep -qE '\bGuezli/mailcow-f2b-bans\b'; then
    ok "Parser active: Guezli/mailcow-f2b-bans"
else
    fail "Parser not loaded. Check: journalctl -u crowdsec --since '1m ago'"
fi

echo ""
ok "Done. Watch for hits with:"
echo "    cscli alerts list --scenario Guezli/mailcow-f2b-feed --since 24h"
